---
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'    
      - match_re:
          severity: '^(none|warning|critical)$'
        receiver: 'MySlackChannel'
    receivers:
      - name: 'null'
      - name: 'MySlackChannel'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/000000000/00000000/00000000000000'
            channel: '#aks-prometheus'
